### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by MrTarantula** [beestat/app#100]
I see in the past you have opted to not open source this, but I would love to be able to run a Docker container on my personal setup. I'm not asking for you to do anything with Docker, just open source it so that it can be done. 

I totally understand wanting to keep the source under wraps, and that there may be infrastructure issues that would prevent it from working correctly (comparing with other user data, etc).

**Comment by ziebelje** [comment]
I've actually changed my mind fairly recently about all that. There's nothing about the source code that I care to protect, but you're right that many of the features won't actually work. Comparisons will be worthless (you'll be 100th percentile I guess :D), and there's a number of external APIs I communicate with that would either need connected or checked for robustness.

I'm not sure exactly when I'll get to this, but I do want to open source it soon. I've got to get 1.3 out, then clean a few things in the code up, then document the very basics of how it works for the few people who might care to attempt to run their own instance, then try to actually run my own instance and see if it works.

So much to do, so little time...

**Comment by MrTarantula** [comment]
Meh, don't worry about any of that. That's what contributors are for! Make ***them*** figure out how to run it.

**Comment by ziebelje** [comment]
Maybe I'll open source it and then try to tackle some of those items on the side. I could maybe release the source code within a month or so. No promises, but I'll see what happens.

**Comment by ziebelje** [comment]
Reply to this thread if you would be interested in gaining early access to the source code. The stipulation is that you must be willing to look over the code and let me know of any issues you see. Mostly looking for a few extra sets of eyes to make sure I haven't done something stupid to jeopardize security.

**Comment by MrTarantula** [comment]
Is it PHP? I only have basic knowledge of PHP, but I work with C#, JS/TS, SQL, and others as needed, so I should be able to read it but I don't have knowledge of best practices for PHP. It's sometimes good to have someone from the outside looking in to find security issues (exposed keys, injecting bad stuff through APIs, etc). I'd definitely like to take a look.

**Comment by ziebelje** [comment]
Yes, beestat runs on a typical LAMP stack. I'm wrapping up some cleanup and my own internal audit right now. Sometime in the next few weeks I will be reaching out to interested parties to give you access to a private repository.

**Comment by vincep5** [comment]
I would be interested in looking to help

**Comment by UnixGuru** [comment]
I too would be interested.  39 years of Unix/Linux experience, not as fresh on PHP as I’d like but well versed on MySQL, Apache, and of course,  the OS.

**Comment by ziebelje** [comment]
Please join this Discord server for any discussion about the source code:
https://discord.gg/TpCq6SY

**Comment by ziebelje** [comment]
I have added you three as collaborators to a temporary private repository. If anyone else is interested please request here so I can send you the invite.

**Comment by ziebelje** [comment]
Project is officially open sourced. Go wild! I'll be making a more formal announcement next. week.
