### ISSUE TITLE
Add menu option of Average Trend in Temperature Profiles 

### ISSUE THREAD

**Issue by vincep5** [beestat/app#104]
It would be nice to see in the graph, the average (community based) home trend line that your house is being compared to [Heat, Cool, and Resist].  Visually, it would be neat to compare my trend line to the average and see how better or worse it is.  It could be a show/hide option in the menu

**Comment by ziebelje** [comment]
I like this idea!

**Comment by ziebelje** [comment]
I liked this idea so much that I created it again and took all the credit for it. #175 

:D
