### ISSUE TITLE
Manually configure thermostat groups

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#107]
Need to be able to manually configure thermostat groups rather than completely depending on address. This will help increase visibility of what thermostats are in each group as well as solve problems where a thermostat needs to be explicitly excluded from a group. For example: If someone has two thermostats but one is a backup or even just an old one sitting around.

**Comment by ziebelje** [comment]
Thermostat groups are going away soon. Bye!

**Comment by ziebelje** [comment]
The only time when two thermostats "interact" in beestat is for the profile generation. There is an implicit grouping based on physical address, and if two thermostats are at the same address they are considered to be part of a zoned system. In this case the profiles automatically exclude data on one thermostat where any other thermostat in a separate zone is running.

Although I can think of edge cases where this doesn't work, I haven't yet run into them.

**Comment by joberembt** [comment]
I have just the scenario for this - I have a detached garage with a furnace in it - I'm contemplating getting a 2nd ecobee to run the garage & give me remote capability, but don't want it mashed in with my house data and would rather not have to have two separate accounts.

**Comment by jlj-pers** [comment]
Thanks @ziebelje. So just to be clear, when I look e.g. at the "Resist" graph on one thermostat, it is as if the other thermostat didn't exist, correct?

Also, I have some sensors e.g. in an attic or a crawl space or outdoors. Those are never part of the comfort settings. Those are graphed (thanks!), but they are NEVER used in the "Resist" graph, correct?

**Comment by ziebelje** [comment]
@joberembt You can handle this in two ways right now. First, set one of the thermostats at a different physical address in the ecobee app. Post office works great. Beestat won't consider them zoned in that case. Alternatively, you can leave them both at the same physical address. Your profiles won't be wrong, they will just have less data to work with. This is because beestat does not sample profile data when *any* thermostat in a zone is running to avoid bleed between zones. So all that happens is that there's fewer data points to generate a profile from. Not a huge deal normally.

**Comment by ziebelje** [comment]
@jlj-pers Each thermostat gets it's own unique profile. If you have thermostat A and B, then thermostat B will block thermostat A from capturing profile data when thermostat B is running. So yes, in general, beestat tries to give you a unique look at each thermostat.

Profile generation uses the temperature displayed on your actual thermostat. Sensors only matter in that they can be part of that average. I just use the ecobee-calculated average temperature for all of my calculations.

**Comment by ziebelje** [comment]
I re-opened this to take another look at the possibility of manually grouping thermostats, or possibly using ecobee's built-in "Home" feature instead.
