### ISSUE TITLE
Issue when switching to Past 12 Month/All Time for Aggregate Runtime

### ISSUE THREAD

**Issue by pmichaelro** [beestat/app#111]
If I try to switch from Past 2 Month to Past 12 Month or All Time the Aggregate Runtime Graph breaks and is stuck to the loading animation. I have data since September 2018 at least.

**Comment by ziebelje** [comment]
Hey! Sorry for not getting to this one sooner. Could you send your thermostat serial to contact@beestat.io (or post it here). I'll get you taken care of. Thanks!

**Comment by ziebelje** [comment]
I am not able to reproduce this on your account; is it still happening for you?

**Comment by ziebelje** [comment]
Since I was unable to reproduce this on your account I believe this issue is resolved. If not, please don't hesitate to reopen this and let me know. Thanks!

**Comment by mihaicristianpetrescu** [comment]
This is still now working for me. It's stuck on "Loading Aggregate Runtime" since logging in.

**Comment by mihaicristianpetrescu** [comment]
Only the past 2 months option is working, the rest lock the widget into "Loading Aggregate Runtime".

**Comment by ziebelje** [comment]
Hey @mihaicristianpetrescu, would you send your thermostat serial to contact@beestat.io? I'll take a look. It looks like there's a larger issue at causing this for a number of users so I'll see what's up and try to get it fixed for everyone.

**Comment by mihaicristianpetrescu** [comment]
I already sent it to you the first time, but I can forward that email again, no problem.

**Comment by ziebelje** [comment]
Apologies, I saw your comment was from a different GitHub user and thought it was for someone else. I confirmed that your data is all correct and I can successfully load everything from my computer. I did a little digging and found this in my error logs:

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
1
File https://beestat.io/js/beestat.js line 497 col 444 in rocket.Elements.removeChild
2
File https://beestat.io/js/beestat.js line 654 col 139 in beestat.component.card.aggregate_runtime.beestat.component.card.hide_loading_
3
File https://beestat.io/js/beestat.js line 648 col 61 in beestat.component.card.aggregate_runtime.beestat.component.card.decorate_
4
File https://beestat.io/js/beestat.js line 634 col 136 in beestat.component.card.aggregate_runtime.beestat.component.rerender
5
File https://beestat.io/js/beestat.js line 654 col 401 in beestat.dispatcher_.<anonymous>
6
File https://beestat.io/js/beestat.js line 594 col 347 in [anonymous]
```

This issue is happening for you on Chrome Mobile 74 on Android. I suspect this would work fine if you tried from a desktop or possibly even a different device, but I'll still try to duplicate and fix this issue.

**Comment by ziebelje** [comment]
I just tested your profile from my phone (Google Pixel, Android 9 running Chrome Mobile 74) and was not able to reproduce.

I'll continue to investigate. Any more detail you can provide about your device, usage patterns, etc would help me to get this resolved for you.

**Comment by mihaicristianpetrescu** [comment]
OS: Mac OS 10.14.5
Chrome Browser: 74.0.3729.169 official build
Safari Browser: 12.1.1 (14607.2.6.1.1)

It's happening on iOS 12.3 as well inside the latest Chrome Browser.

So it's a widespread issue happening all over the place.

**Comment by ziebelje** [comment]
Could you help clarify something? You report this is happening on a Mac OS (in both Chrome and Safari), as well as an iPhone (in Chrome ind Safari), correct?

The user agent string I'm getting in my logs is:
> Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Mobile Safari/537.36

If you look that up it's a Google Nexus device running Android 6 and Chrome 74. Not saying I don't believe you, just trying to understand why my logs say it's a Nexus/Android device but you're reporting to use iOS devices.

Additionally, the first time it happened was on 5/3, which looks like it was the first time you used beestat. So from what I can tell this has never worked for you. I've tried using BrowserStack to emulate both Nexus and iOS devices but haven't been able to reproduce it yet.

You're also the only user I see this specific error in the logs for, so I have always been testing as you. Really not sure yet but I'd like to get to the bottom of this.

**Comment by mihaicristianpetrescu** [comment]
Both Mac OS and iOS, Chrome and Safari.
It never worked for me, correct.
If I can assist you in any way, let me know.
