### ISSUE TITLE
Ecobee does not purge historical data when a thermostat is registered to a new user

### ISSUE THREAD

**Issue by coneslayer** [beestat/app#115]
I'm a new Ecobee and Beestat user. (I'm actually the guy who just asked for oil aux heat on Reddit--thanks for implementing that so quickly!)

I understand that, at first, the Home Comparisons data is likely to be noisy and poor quality. However, I think my data is "contaminated" with erroneous data. If I'm reading the graph right, there's heating data down to 20 F, and resist data down to about -8 F:

![Temperature Profiles](https://user-images.githubusercontent.com/4835005/57653419-c19c3300-759f-11e9-9453-85c25dbad8c1.png)

However, since I installed my Ecobee last Friday, the lowest temperatures here have been in the low 40s.

I do have one hypothesis: I bought my Ecobee as an open-box unit from Amazon. I reset it and went through the new-user setup, and I created a brand-new Ecobee account. But the Thermostat Info shows a "first connected" date several months ago, well before I purchased it:

![image](https://user-images.githubusercontent.com/4835005/57653657-59018600-75a0-11e9-9cdf-9ef2be1a9b65.png)

I'm suspicious that my data are contaminated by the original purchaser's data. Is there any way to expunge or ignore all the data before the date that I set it up? It seems like this issue would also affect people who move to a new home and want to start fresh.

**Comment by ziebelje** [comment]
Would you do me a quick favor? Go poke around on the your Home IQ reports on ecobee's website and see if you see older data. It looks like the previous owner pulled it off the wall around Feb 8 so check before then.

As far as I know ecobee stores all the data uniquely by serial number. I've heard one other person mention that they saw the previous owner's runtime data, although no personal information was ever exposed. When you hooked this thermostat up to beestat I was able to see all of the historical data because that's how far back ecobee gave me.

I can do a one-time purge of the invalid data on your account, but I'd like to see if there's a more appropriate way to fix this moving forward.

**Comment by coneslayer** [comment]
Thanks for looking into this.

On the Ecobee website, for "Runtime Report", I get messages like "December's Runtime Reports Are Underway" for every month going back to December 2018, which is the earliest month I can select. I get similar messages for "Community Comparisons" and "Home Efficiency".

Under "System Monitor", I can scroll back to January and see somebody else's data under "System", "Schedule", and "Weather Impact." I don't see anything that's personally identifying, but it looks like real data corresponding to the previous owner's home.

![image](https://user-images.githubusercontent.com/4835005/57665294-464f7700-75c9-11e9-91d6-cb097b4875ab.png)

Interestingly, if I go to "Download Data", select some dates, and try to download the data, I get a "login failed" error. This happens whether the dates correspond to the previous owner (e.g. January 1-31, 2019) or myself (e.g. May 11-13, 2019).

![image](https://user-images.githubusercontent.com/4835005/57665317-5f582800-75c9-11e9-9fc7-e56fc9a7e4a3.png)

Please let me know if I can provide any more information.

**Comment by coneslayer** [comment]
If it won't hurt your efforts to solve this properly, could you go ahead and purge any data for my thermostat prior to May 10, 2019? Thanks!

**Comment by ziebelje** [comment]
You got it! Deleted 37,440 rows. If this data ever needs restored for some reason I can flip a flag to cause all of your data to re-download from ecobee. Note that this won't change your thermostat first connected date as displayed in the UI. I actually rely on that field to help identify unique thermostats (apparently a mistake) so I can't change that value without messing some other stuff up.

**Comment by ziebelje** [comment]
At the moment the most economical way for me to handle this is to delete the data manually.
