### ISSUE TITLE
Authorization problems from ecobee site

### ISSUE THREAD

**Issue by intel1212** [beestat/app#118]
Weird.  Was able to connect to the beestat.io site a few days ago, from a chrome browser on macOS.  Starting last night, I would get the following error:

Authorize
We're sorry but we were unable to complete your request. Please try again.

will have permissions to view the thermostat settings and data in your account.

Application Summary:
Application Description:

I was already logged in to my ecobee account and reviewing my settings.  From same browser session, would go to beestat.io, select Ecobee icon and received the message above.  Other data points.  I tried same process with Safari on same mac, no problem!

I removed history for last 7 days (just installed my ecobee3 lite devices on a few days ago).  Same problem.  I wonder if I have a plugin type issue.  Anyway, recording issue and will update if I figure out.

**Comment by ziebelje** [comment]
That happens if you're logged into the ecobee website when you try to authorize a third party application like beestat, IFTTT, etc. See #44.

It should work if you actually log out of the ecobee website and then reload beestat.
