### ISSUE TITLE
Statistics and other information

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#120]
Add some sort of statistics/informational card or page with lots of detailed statistical information.

Ex:
A statistic that would be really useful is if beestat could display the average, minimum and maximum contiguous runtime for a compressor or heat-pump. Along with the standard deviation.
(https://www.reddit.com/r/beestat/comments/bt2i39/suggestion_minmaxavg_runtime_stdev/)

**Comment by ziebelje** [comment]
Probably call this "Home Report"

**Comment by netengmonty** [comment]
ELK stack could potentially be perfect for this. I wish I had the availability to build this out and contribute 😔

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/statistics-and-other-information/322
