### ISSUE TITLE
Set temperature says -400 when on vacation

### ISSUE THREAD

**Issue by vincep5** [beestat/app#122]
![Screenshot_20190604-162521~2](https://user-images.githubusercontent.com/26965876/58920133-b1cac700-86e5-11e9-8e78-3e56e045c7fd.png)
While on vacation mode, I'm seeing the heat temp at -400. Probably because I've set it to only cool.  Might be worth looking into.

**Comment by ziebelje** [comment]
I've seen this before but only when thermostats or sensors get removed from an account. I'll take a look at how it responds in vacation mode and get that cleaned up. Thanks for the report!

**Comment by ziebelje** [comment]
This should be fixed.
