### ISSUE TITLE
Removed sensors are not being properly removed

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#125]
A couple users have removed sensors from their ecobee but they continue to show up in beestat.

**Comment by ziebelje** [comment]
I identified two issues:
- Sensors that were marked as inactive could never be marked as active again if they came back
- The marking of inactive sensors was incorrect and would cause "random" sensors to be incorrectly marked as inactive when there was at least one other sensor being marked as inactive.

**Comment by scunnyngham** [comment]
Thanks for this fix!
