### ISSUE TITLE
Show timestamp for when data was last updated

### ISSUE THREAD

**Issue by intel1212** [beestat/app#126]
Idea.  Time stamp visible for last update, or time of data from ecobee.  Perhaps along with a count-down icon/bar/digits of when to expect new data or update.

**Comment by ziebelje** [comment]
Yeah I could probably swing something like this. I'll take a look. Good idea!

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/show-timestamp-for-when-data-was-last-updated/312
