### ISSUE TITLE
Home Comparisons is stuck on Calculating Scores

### ISSUE THREAD

**Issue by johnsaboe** [beestat/app#130]
When I click on the Home Comparisons tab, it perpetually shows "Calculating Scores". It was working initially, but has been stuck whenever I try to access it for at least a week or two. I did recently update some of my property info on EcoBee's site (it was previously incorrect), but I'm not sure if Calculating Scores started getting stuck before or after this (or if it's related at all).

Thanks!

**Comment by ziebelje** [comment]
Hi! Could you send me your thermostat serial? Either post it here or email it to contact@beestat.io. I can take a look.

**Comment by ziebelje** [comment]
I think this one is resolved as I don't have anything outstanding in my email to resolve. Closing this but shoot me that email if there are any issues.

**Comment by cbbowman** [comment]
I am also experiencing this issue. I just installed two ecobee4's and both are stuck on "Calculating Scores"
