### ISSUE TITLE
Add high/low on aggregate runtime

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#131]

**Comment by ziebelje** [comment]
![image](https://user-images.githubusercontent.com/3288812/61259510-860d1900-a748-11e9-8a22-6c79a09a6210.png)

**Comment by mwidjaja1** [comment]
Hey! Matt Widjaja here (from Patreon), this looks awesome!

**Comment by ziebelje** [comment]
This took an extra minute because my graphing library (Highcharts) has a bug in their custom build tool. I tried to rebuild it to add a new series type (AreaSplineRange) and it broke everything. Reported that bug and resolved the issue manually for now. This should be going live soon. Thanks, @mwidjaja1 for your suggestion!
