### ISSUE TITLE
Chart absolute humidity in air

### ISSUE THREAD

**Issue by ghfields** [beestat/app#132]
The relative humidity thrashes around as the temperature fluctuates.  Could you have an option to display absolute humidity (water weight in air)?  (EDIT: Dew Point would be a good measure of this, thanks @daintytomato) 

https://www.engineeringtoolbox.com/water-vapor-air-d_854.html shows 70 degrees 70%rh = 75 degrees 60%rh = 80 degrees 50%rh

By looking at absolute water vapor, you could tell if you are humidifying your house by opening your house during a cool night.

**Comment by daintytomato** [comment]
I second this.  An alternative metric that could provide this information would be dewpoints.  It'd be awesome if you could view the outside and inside dewpoints temperatures.  If the dewpoint outside is lower, then you know you won't be adding humidity to your house when you open your windows.

A benefit to using dewpoint as a metric would be that you could get an idea of whether stuff is going to condense in your house (or the cooler rooms of your house) based on the temps in those rooms and the dewpoint temp.  It also has the same units as temperature and could easily be plotted on the same graphs (vs. absolute humidity of 0.005 lbs water vapor per lb air).

It would be awesome if this could be added!

**Comment by ghfields** [comment]
I agree.  Dew point is a much more known metric to describe absolute humidity.  

In Celsius (+-1%):
Dew Point=Temperature - ((100-Relative Humidity)/5)

Or you could get even more accurate with another found on https://en.wikipedia.org/wiki/Dew_point

**Comment by ziebelje** [comment]
Hey guys, thanks for the great feedback. Let me do a little reading to make sure I have a proper understanding of all this. At a glance it doesn't sound too bad and I've had a bit of other feedback about humidity so this is something I'd like to improve. Stay tuned!

**Comment by ziebelje** [comment]
Dew point is present in the weather data provided by ecobee (originally provided by DarkSky). It is not available historically.

1. I have no idea if dew point is measured or calculated.
2. I can calculate dew point historically with temperature and RH (https://www.omnicalculator.com/physics/dew-point)

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/chart-absolute-humidity-in-air/321
