### ISSUE TITLE
Add lines for design temperatures to chart

### ISSUE THREAD

**Issue by ghfields** [beestat/app#133]
A properly AC and heat should be running almost constantly at design temperatures for the geography.  It would be nice to be able to add lines to reference those temperatures.

I don't know if there is by datasource that could do this off the already known region, or if it could just be a user provided number.  (automated would obviously be preferred)

This would help when people ask for help and share a chart.  People would have some idea what the geographic expectations of the system are.

**Comment by ziebelje** [comment]
This is probably just #175 . It would be impractical to find source data for all this, and the number of users who would manually populate it is nearly 0. A better approach is to just display a second profile for all of the homes in your comparison group. It won't be comparing you to "ideal", but it's the next best thing.
