### ISSUE TITLE
Beestat demo site not loading for registered users

### ISSUE THREAD

**Issue by vincep5** [beestat/app#134]
This might not be much of an issue, but when I navigate to https://demo.beestat.io/ the loading indicator just spins endlessly.  I think it has to do with the fact that I am already a registered user and my browser might be trying to log me in automatically.  When I go into Incognito mode, the demo site does load up fine.

**Comment by ziebelje** [comment]
Confirmed issue. I think it's something to do with the cookie domain configuration. Thought I had all that properly separated but I guess not. I'll take a look at this eventually...
