### ISSUE TITLE
Cooling and Fan runtime graph is a little off

### ISSUE THREAD

**Issue by vincep5** [beestat/app#138]
![image](https://user-images.githubusercontent.com/26965876/61544594-6a856500-aa0b-11e9-9b7d-04512858e006.png)

At the end of the cycle my HVAC fan runs for 3 mins longer.  The graph did show this fine up until today.  Now its skewed going the wrong way.  Looks like the beginning part is off by a few pixels

**Comment by ziebelje** [comment]
Looks like I accidentally pushed some code live related to #121. It wasn't ready for prime-time yet. I'll figure it out and roll back tonight. Thanks for the report!

**Comment by ziebelje** [comment]
This should be fixed now.
