### ISSUE TITLE
Display current outdoor weather

### ISSUE THREAD

**Issue by coneslayer** [beestat/app#141]
If the API provides it, I would be interested in seeing the current outdoor temperature and humidity in the "System" panel that shows the current thermostat status and indoor temperature/humidity.

**Comment by ziebelje** [comment]
Yes, ecobee provides this information. More information on the available fields here:
https://www.ecobee.com/home/developer/api/documentation/v1/objects/WeatherForecast.shtml

I'll add temperature/humidity, but since I'm doing weather I might as well add a bunch of other fields as well. Give me a few days to map everything and test.

**Comment by ziebelje** [comment]
Here's what's being added:

![image](https://user-images.githubusercontent.com/3288812/61878325-cd20aa00-aebe-11e9-8014-20cfa2381989.png)

**Comment by ghfields** [comment]
Do I see a dew_point listed there :)  
#132

**Comment by ziebelje** [comment]
Shh, you weren't supposed to notice yet!

**Comment by ziebelje** [comment]
Any last requests?

![image](https://user-images.githubusercontent.com/3288812/61954420-d2492c00-af86-11e9-8b47-66124862c416.png)

Clicking on the outdoor bubble takes you here:

![image](https://user-images.githubusercontent.com/3288812/61954425-d5441c80-af86-11e9-944e-953e3807112b.png)

**Comment by coneslayer** [comment]
I like it!

**Comment by ghfields** [comment]
That's pretty cool.  Might give some people momentary confusion with a lack of labels for the circles, but they should easily overcome that.   I don't think it's worth cluttering the UI for that.

**Comment by ziebelje** [comment]
Yeah I think some people may confuse it for a setpoint at first but I think they'll figure it out. I couldn't come up with any way to distinguish them without adding text or an icon which I don't want to do. This change should probably go live tonight.

**Comment by ziebelje** [comment]
Sending live shortly.
