### ISSUE TITLE
Add fan, humidifier, dehumidifier, etc to Runtime Summary

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#142]
In order to add all these possibilities I need to add a customization modal to each chart in order to better limit the available legend options. For example, you can only have one accessory at a time so showing all possible accessories on the legend always would just be silly.

**Comment by ziebelje** [comment]
Need to do #143 first.

**Comment by adamobringer** [comment]
I'm a huge fan of this feature.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/add-fan-humidifier-dehumidifier-etc-to-runtime-summary/102
