### ISSUE TITLE
Eco+ causing errors

### ISSUE THREAD

**Issue by sup-one** [beestat/app#144]
Just signed up for the Eco+ from Ecobee and getting the following error:

{
  "success": false,
  "data": {
    "error_message": "Database query failed.",
    "error_code": 1206
  }
}

Once in a while I also get error that the object doesn't support property "forEach"

Eco+ creates new comfort settings to manage energy use and these do not show up in beestat - just blank spaces in the graph.

**Comment by sup-one** [comment]
Got another error this morning:

API call failed: Out of memory (allocated 41197568) (tried to allocate 20480 bytes)
Sorry about that! This error has been logged and will be investigated and appropriately punished. Please reach out to contact@beestat.io if it persists.
{
  "success": false,
  "data": {
    "error_message": "Out of memory (allocated 41197568) (tried to allocate 20480 bytes)",
    "error_code": 1
  }
}

**Comment by ziebelje** [comment]
Working through these...the "forEach" error is #146 and appears to be mostly resolved.
