### ISSUE TITLE
Unable to Sync/Load

### ISSUE THREAD

**Issue by lindsaygilmore** [beestat/app#147]
Currently unable to sync recent activity or load aggregate data. Logging out/in, clearing app cache/data, or uninstalling/reinstalling seem to help.

**Comment by ziebelje** [comment]
Hi Lindsay! Would you mind to send your serial number to contact@beestat.io? I'll take a look.

**Comment by ziebelje** [comment]
Closing for now due to lack of response. Please let me know if this continues to be an issue.

**Comment by lindsaygilmore** [comment]
No worries. I found the issue to my user error on my end. Somehow, my
phone's date and time were off and this affected me getting the app to
operate properly.
