### ISSUE TITLE
Energy Saving Event not recognized

### ISSUE THREAD

**Issue by brandiniman** [beestat/app#152]
A triggered energy-saving event isn't recognized on the activity graph yet. It seems to pick a random comfort setting on the top color bar and setpoints don't change either.

**Comment by ziebelje** [comment]
Hi! Would you send me your thermostat serial and a date/time when this happened? Should be an easy fix.

**Comment by ziebelje** [comment]
Closing this unless further info is provided.

**Comment by brandiniman** [comment]
I just got a new tstat so all my historical data may be toast... I'll resubmit this summer!

**Comment by brandiniman** [comment]
I made a lot of repairs and settings changes recently so I'm going to embrace the clean slate!
