### ISSUE TITLE
Home Comparisons is stuck on Calculating Scores

### ISSUE THREAD

**Issue by cbbowman** [beestat/app#153]
When I click on the Home Comparisons tab, it perpetually shows "Calculating Scores". I just installed two ecobee4's and both are stuck on "Calculating Scores"

**Comment by cbbowman** [comment]
Problem shows up both on the Android app, as well as browsers on iOS and Android.

**Comment by ziebelje** [comment]
Wow this was from August. :/ Could you post your thermostat serial here or email it to contact@beestat.io? I can take a look.

**Comment by ziebelje** [comment]
Closing for now due to lack of response. Please let me know if this continues to be an issue.
