### ISSUE TITLE
Add chart for sensor data

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#17]
> Make a plot that shows average home temp vs sensor temp so we can use it to accurately tweak vent settings for both heat and cool? Maybe a trending over the past (range) since it'll change with the seasons. Maybe a few ways to see if a room has poor insulation vs too much airflow (temp delta at end of runtime vs at beginning of runtime, etc)

https://old.reddit.com/r/ecobee/comments/8hw7qd/analyze_your_hvac_usage_and_home_efficiency_with/dynb7e0/

**Comment by ziebelje** [comment]
@john5788 #32

**Comment by jballow** [comment]
I would love individual sensor temp / humidity graphs with set temp

**Comment by jljimene** [comment]
The ability to plot the data from different sensors would be extremely useful. I am frankly shocked that this feature is not there either in Ecobee or BeeStat already. This would allow seeing much better how different rooms are responding to the HVAC and to the outside weather. Which then would allow adjusting the vents accordingly.
I also want to be able to monitor temperatures in our crawl spaces, where there are some pipes that could freeze. Those temperatures track the house and outdoor temperatures, but typically get coldest in the middle of the night when I am not looking at the app etc.

**Comment by ziebelje** [comment]
Closing this issue; new feature to go live Feb 11th. :)

![image](https://user-images.githubusercontent.com/3288812/74035925-411d2e00-4989-11ea-85cc-f1cdd49b426e.png)
