### ISSUE TITLE
Factor weather conditions into Runtime Summary and Temperature Profiles

### ISSUE THREAD

**Issue by starcms** [beestat/app#174]
Is there any way in a future update to factor whether it is sunny or cloudy into the cool score, resist score, and temperature profiles?  Our attic is poorly vented and insulated, and on a cloudy day the AC runs a fraction as much as a sunny day, at the same exterior temperature (80+ F specifically). So my resist scores in particular can vary wildly week to week. 

Also, just adding the weather conditions (sunny, cloudy, etc) to the tooltip for the runtime summary would be a big help.  I realize that's alot of info, but you could do just calculate and display an average during daylight hours saying if it was a very sunny day, very cloudy day, or mixed for each day. 

Thanks much!

**Comment by ziebelje** [comment]
This is unfortunately not possible. While I do have access to weather data, it's only instantaneous. Basically when you access beestat is when I fetch updated weather data. Being able to reliably determine sky conditions for this purpose would require massively increasing the number of API calls I send to ecobee which isn't sustainable. Using a third party weather service would also cost over $100/month for mediocre results. The place I fetch historical data from does include a "sky" value, but it's always null and so is useless as well.

That said, all of the temperature profiles factor in an entire year of data. While I agree it would be nice to see how your profile changes on sunny vs cloudy days, your score is still going to be averaging a good amount of data together and so should be fairly stable. Same story for the Runtime Summary chart. That would actually be neat to display but I just don't have the data available to do it.

I think if I were to pursue this in the future it would have to be a paid (like $1/month or less) "Weather Impact" feature to cover the cost of querying a third party weather service. I could then get information like wind, sky, precipitation, humidity, etc.

I'll keep this open as an "Idea". I think there's potential for doing some cool stuff with weather conditions but I would probably not get to this any time soon. Thanks for your feedback!

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/factor-weather-conditions-into-runtime-summary-and-temperature-profiles/317
