### ISSUE TITLE
outage last night?

### ISSUE THREAD

**Issue by vincep5** [beestat/app#177]
in this screenshot, the time start to end is 1:40 to 3:10am  but when I hover with my mouse, it skips from 1:40 to 3:00am.  It shows this span as only 15 mins of runtime.  It should show 5minute intervals if I move the mouse on the chart, but for a few hours overnight, but it looks to have skipped some intervals.

![image](https://user-images.githubusercontent.com/26965876/68136053-3e262380-feea-11e9-95d8-e970ceb6bd73.png)

**Comment by vincep5** [comment]
Previous screenshot was probably related with an Ecobee outage, as that data is also missing during that night.  
Another related issue is that if my WiFi has an outage, Ecobee will save the info until a connection is re-established.  I think I visited Beestat before the Ecobee could send up the missing data and thus there is an interval for 11/29/19 between 12:45 and 5:45am that is missing from Beestat but is there in the HomeIQ in Ecobee.

**Comment by ziebelje** [comment]
I'm wrapping up a few things on this chart now so I'll investigate this before I send the new version live.
