### ISSUE TITLE
Display data in PC local time or thermostat local time?

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#191]
> I figured it out, I'm using Firefox and tweaked the fingerprinting setting. This came back when I searched the web:
> 
> timezone shifting can happen when you tweak the privacy.resistFingerprinting preference in about:config.

**Comment by ziebelje** [comment]
Options:
- Continue relying on `Intl.DateTimeFormat().resolvedOptions().timeZone;` and moment to pick the correct time zone
- Do some moment configuration to set the time zone to the thermostat time zone

**Comment by ke4roh** [comment]
I'm going to recommend using the thermostat time zone.  When I was in Germany trying to program my thermostat in North Carolina, it was a bit nuts.  The Ecobee app wouldn't let me set the times I wanted because they had already passed on my phone!

**Comment by ziebelje** [comment]
Bump :)

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/display-data-in-pc-local-time-or-thermostat-local-time/314
