### ISSUE TITLE
iOS Add to Home Screen not working

### ISSUE THREAD

**Issue by jayjanssen** [beestat/app#211]
Viewing my logged in dashboard in iOS safari and I use ‘Add to Home Screen’ to create a home screen icon.  When I open this button I’m getting a ‘Not Found’ error.  Is there a way to correct this?

**Comment by ziebelje** [comment]
This has been broken for a while...thanks for reporting it. When pinning the app it was pinning app.beestat.io/dashboard which is old/invalid.

Note that it can sometimes be difficult to get your device to get this update. If you have trouble, close all apps, clear the Safari cache, reboot, then try again.
