### ISSUE TITLE
Increase refresh rate / Live Dashboard

### ISSUE THREAD

**Issue by adamobringer** [beestat/app#213]
A few things would be useful if configurable for folks that use Beestat as a 'portal' display showing semi-realtime info.

- Thermostat status (immediate state of temp, etc specific to your Ecobee) would be nice if it were able to be brought down to a minimum of every 10-15s (then perhaps 1m, then the 5m default) for anyone using a 'portal' style device that constantly shows status. Beestat is way cooler than the actual app for this, especially when you don't want the device to be able to natively control the stat. Obviously this can't go TOO far down due to throttling on the API, but I've been able to keep data refreshing manually by hand at least once every few seconds, so something realistic like 10-15s would be awesome to ensure data is current.
- Website refresh interval would also be nice if configurable down to match the above so that data refreshes happen parallel as it syncs from the API. I'd imagine you'd want this to be the same as the above value honestly.

I wouldn't go as far as to ask that we do anything with the actual charting refresh interval. It's historical data and can take its' time at the default 15m IMO without folks changing it around. I suppose it's up to you though. I'd imagine you don't want the extra traffic, looking at this from a NetOps POV :)

**Comment by ziebelje** [comment]
From ecobee:
> DO NOT poll at an interval quicker than once every 3 minutes, which is the shortest interval at which data might change.

Today, if you have beestat open, it will refresh the thermostat and sensor data once every 5 minutes. That said, it's my experience that changes are present in the ecobee API quicker than that.

I probably wouldn't have a problem shortening from 5 to 3 minutes, but I understand that if you're using beestat as a live dashboard you could hear your system turn off and beestat could lag behind by three minutes.

If I were to do this, I would probably prefer to create a "dashboard mode" that has a different collection of cards and a faster refresh rate. What information are you typically looking at on beestat for your dashboard and how do you use that information?

**Comment by ziebelje** [comment]
#126

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/increase-refresh-rate-live-dashboard/311
