### ISSUE TITLE
Highlight Weekends or Away vs Home %

### ISSUE THREAD

**Issue by tibble** [beestat/app#219]
In the Runtime Summary chart it would be nice to highlight/shade/mark weekends vs weekdays.  Alternatively maybe put the number of hours away vs home to meet more peoples schedules?

I would love to be able to visually determine if it was a day that we were at our Away temp more than others.

**Comment by ziebelje** [comment]
Just trying to understand a bit better:
Are you trying to see how much time your home was in "away" or "home" mode so you can see how that correlates to runtime?

**Comment by tibble** [comment]
> Just trying to understand a bit better:
> Are you trying to see how much time your home was in "away" or "home" mode so you can see how that correlates to runtime?

Exactly. I am getting insulation installed and want to compare before/after. The ecobee history shows a grey circle around the weekend dates. That would be a good start but I thought beestat could go one further and determine if you were mostly away. That would help people with different work schedules that work weekends but have off weekdays. It would also help for sick days, vacation days at home, etc. 

not sure if it would be an automatic detection of typical away hours or just a manual setting, I.e.:
hours away required for a normal ‘work day’.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/highlight-weekends-or-other-intervals-on-charts/19
