### ISSUE TITLE
Add Evaporative Cooling (Swamp Cooler) Type

### ISSUE THREAD

**Issue by bbrannon4** [beestat/app#225]
I know Ecobee doesn't (yet) support swamp coolers, though I don't think I'm the only one who has used the DX Compressor settings to control a swamp cooler.  Having the option to manually select it on beestat may help with some of the cooling scoring algorithms.

**Comment by ziebelje** [comment]
One of the problems with this would immediately be adoption. Heat and cool scores are pegged to your system type; that's not changeable. If I added Swamp Cooler as an option and you switched to it, you would instantly have nobody to compare to.

I'll have to do some research on Swamp Coolers to see whether or not that's a good idea. :)

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/add-evaporative-cooling-swamp-cooler-type/308
