### ISSUE TITLE
Notifications for temperature thresholds from individual room sensors.

### ISSUE THREAD

**Issue by jfoj** [beestat/app#232]
Would like to have the ability to trigger alarms/email messages/text messages for temperature thresholds from individual room sensors. 

Not sure this is possible, but would be a GREAT feature to have. While the thermostat can send threshold alarms for the thermostat temperature itself, there does not appear to be a means/way to send threshold alarms for individual room sensors. I have not even found a way with IFTTT.

I have a 2nd home with room sensors in unconditioned areas of the house where I have water lines and I need to be alerted if the temperature drops to a specific temperature so the set back temperature can be increased and/or other action be tanken.

Might even be great if a minimun temperauture threshold was hit that the thermostat could be commanded to increase or change the temperature in an attempt to counter act the low temperature in the unconditioned space.

Thanks for your efforts and considering this type of feature.

**Comment by ziebelje** [comment]
Is this a feature you would be willing to pay for? Emails and text messages cost money to send*, plus I would have to sync your information every 5 minutes or so even when you're not using beestat which is additional server load.

I've always wanted to do text/email reports and notifications, but want to make sure the cost is covered.

*Emails can be done free-ish, but I don't want to manage that infrastructure.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/notifications-for-temperature-thresholds-from-individual-room-sensors/306
