### ISSUE TITLE
Heat/cool differential alerts show up even if you don't have that system

### ISSUE THREAD

**Issue by sqrl0** [beestat/app#246]
I don't have air conditioner, heat only. App showed alert about cooling threshold being below recommended value. Believe it was set at default 0
3.

Tried to change threshold but there was no cooling threshold option on thermostat. Only heat differential which is set to 1.4 degrees. 

Recommend logic to avoid alerting about cooling threshold on heat only system. 

Love the app. Thank you for all your work!

**Comment by ziebelje** [comment]
Thanks for the report! This fix will go live sometime next week with the next release.
