### ISSUE TITLE
Plot Sensors' Outdoor temperature on right Y-Axis

### ISSUE THREAD

**Issue by ac-haynes** [beestat/app#257]
Problem: Clicking to add the Outdoor Temperature line to the Sensor Detail page results on the sensor data being squashed in the 25-19C range when the outdoor temperature is not in the same ballpark as the indoor temperature. For example -5C causes the min/max values on the graph to be -10C and 30C.  With the outdoor temperate at -20 the min and max values of the Y-axis are 40C and -40C

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/plot-sensors-outdoor-temperature-on-right-y-axis/304
