### ISSUE TITLE
Thermostat Detail does not show Away

### ISSUE THREAD

**Issue by vincep5** [beestat/app#258]
My Thermostat Detail shows "Hold" instead of my Away comfort profile.  Not sure if you are able to see what profile is causing the hold.   I'm not sure what HomeIQ says.  They finally fixed it, because I am not able to navigate to it when I click it from the Ecobee UI :)

I do use HomeAssistant to set my Ecobee "Away" so not sure If that is any different than setting it "Away and hold" on the web or "Away for now" in the app

Then you could be using that sort of home vs away data for some possible metrics

![image](https://user-images.githubusercontent.com/26965876/75394056-f4a47e80-58b4-11ea-97d6-4678a3a9319c.png)

**Comment by ziebelje** [comment]
Related: 
> The situation is that my thermostat is in Away mode, set via a HomeKit automation (when the last of us leaves the house). Is it possible to display that more clearly in Beestat (“Away” instead of “Home/overridden”)? Or does the API not provide enough information?

![image1](https://user-images.githubusercontent.com/3288812/75482860-9be7eb00-5973-11ea-9995-81b0da129025.png)
![image0](https://user-images.githubusercontent.com/3288812/75482862-9be7eb00-5973-11ea-8ee0-06872cb862f4.png)

**Comment by ziebelje** [comment]
I'll investigate this and report back. To my knowledge, third party integrations don't do anything except set a custom hold.

**Comment by ziebelje** [comment]
I'm going to go ahead and close this one, but if there's still an issue hit this issue up and we can take a look with some fresher data.
