### ISSUE TITLE
Switch from Rollbar to Sentry

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#263]

**Comment by rnavarro** [comment]
@ziebelje 
Just out of curiosity - Why the change?

Features?
Price?
Something else?

(I don't work for them, but as a fellow dev I'm always curious)

**Comment by ziebelje** [comment]
I honestly just feel like Sentry beats out Rollbar in nearly every category. Not by a lot, but it has that extra bit of polish. I'm operating in the free tier so price isn't a factor, but Sentry's next level up is cheaper if I ever get there.
