### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#271]
```
{
  "success": false,
  "data": {
    "error_message": "Invalid JSON",
    "error_code": 0
  }
}
```

**Comment by ziebelje** [comment]
This is happening because I used my entire address lookup quota this month and the auto-renewal is only on for the free tier. Working on fixing this.

**Comment by ziebelje** [comment]
The next free tier renewal is in three days and the minimum buy-in is $50/month for the next tier. I will see if I can build a workaround that fixes the issue temporarily.

**Comment by ziebelje** [comment]
I especially like that their API doesn't return valid JSON when this happens. :)

![image](https://user-images.githubusercontent.com/3288812/82370055-ed899a00-99e5-11ea-9a86-73d9ba1bda8a.png)

**Comment by ziebelje** [comment]
Beestat no longer breaks completely when my address validation service goes down or returns an invalid response. However, what will happen is that comparisons won't work properly until the address can be validated. In this particular case, that will auto-resolve for most users on 5/22 when my free tier address validation renews. I am working on a way to reduce my lookup volume or otherwise pay for the service (min $50/month) to completely resolve this.

**Comment by vincep5** [comment]
Sounds expensive. Can't it be cached since addresses don't often change? Or am I thinking too simply? Is this the API which helps with finding nearby homes to compare?

**Comment by ziebelje** [comment]
I get addresses from ecobee, but they aren't consistent. One address might be in "IN, USA", and another might be "Indiana, US". Because of the inconsistencies I don't trust the data so I feed everything into an address validation service ([SmartyStreets](https://smartystreets.com/)) which lets me pass all sorts of crazy address strings and then sends me back super normalized address with latitude/longitude data. Works for both US and International addresses. Once I have the coordinates there's a [pretty simple equation](https://github.com/beestat/app/blob/master/api/thermostat_group.php#L716) that I can use locally to find nearby homes.

Here are my US lookups. The first 250 every month are free and my "startup" allowance has expired which is why this is happening now.
![image](https://user-images.githubusercontent.com/3288812/82398669-6b1ecb80-9a21-11ea-9e8c-4f36859be714.png)

I aggressively cache all responses, but between new users and address changes there's still a lot.

**Comment by ziebelje** [comment]
Partially improved with #282.
