### ISSUE TITLE
Added 2nd Ecobee Thermostat and missing thermostat details

### ISSUE THREAD

**Issue by jaredneedellca** [beestat/app#274]
I had one ecobee thermostat and added a 2nd one to my account. On the beestat site I can switch to the 2nd thermostat which shows the current temp but the graphs that show the temperature/humidity history just shows no data to display. On the first thermostat, all information is showing as usual.

I've tried logging and out and relinking the app but no success.

**Comment by ziebelje** [comment]
Since I failed to respond to this **8 months ago** I'm going to assume this is resolved. If not, send your thermostat serial number to contact@beestat.io and I can take a look.
