### ISSUE TITLE
Add sensor data to CSV

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#275]

**Comment by ziebelje** [comment]
![image](https://user-images.githubusercontent.com/3288812/84147879-1cff5580-aa2c-11ea-85b5-bc94bb346e3f.png)

**Comment by bmclaren** [comment]
Just looking at the update, and found this.

        // Return temperatures in a human-readable format.
        foreach(['indoor_temperature', 'outdoor_temperature', 'setpoint_heat', 'setpoint_cool'] as $key) {
          if($runtime_thermostat[$key] !== null) {
            $runtime_thermostat[$key] /= 10;
            if(
              isset($thermostat['setting']['temperature_unit']) === true &&
              $thermostat['setting']['temperature_unit'] === '°C'
            ) {
              $runtime_thermostat[$key] =
                round(($runtime_thermostat[$key] - 32) * (5 / 9), 1);
            }
          }
        }

If the user preference is in °C, why convert it to F for the download?  C is human readable too :)

**Comment by ziebelje** [comment]
@bmclaren It's actually the opposite. :) The database stores all values in °F. If the user preference is °C, it converts the temp from °F to °C.

The "human-readable" comment also refers to the division by 10, not the temperature unit. I added the temperature unit conversion at a later date and didn't do a good job updating the comment to reflect the new contents of that block.
