### ISSUE TITLE
Add Sensor Calibration

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#276]
https://community.beestat.io/t/137

Add support for calibrating the viewed temperature output of sensors. Might as well do thermostats as well. My initial thought is to put this on on an equipment card on a settings page.

**Comment by bmclaren** [comment]
There is an option in the thermostat that I am experimenting with.  (Settings -> Installation Settings -> Thresholds -> Temperature Correction)

Temperature Correction: If you notice that the ecobee’s temperature sensor may be slightly off, you can adjust this + or – 10 degrees for a more accurate reading.

Looking to see if this affects the downloaded data.  The description seems to indicate it is a display offset, but I have changed mine to the maximum offset.   Will look to see a big swing in the one temperature.

**Comment by bmclaren** [comment]
Confirmed.  The setting mentioned above is a offset for the in-thermostat temperature sensor.   The offset is reflected in the data for that sensor that beestat downloads.   The displayed temperature on the thermostat appears to be the calculated temperature based on all the ecobee magic (occupancy, sensor active during comfort setting, etc).   So, I would think that you would not want to give the option to offset the in-thermostat sensor data.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/137
