### ISSUE TITLE
Sensor runtime chart colors hard to differentiate

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#296]
https://community.beestat.io/t/sensor-graph-colors/214

> I now have seven sensors, & on the sensor graph, the yellow seems a bit too close to orange to easily distinguish. Perhaps a little less red in the color?

**Comment by ziebelje** [comment]
Current color list: 
![image](https://user-images.githubusercontent.com/3288812/90196828-e1219d00-dd9a-11ea-9372-880b7cfa91f7.png)

**Comment by ziebelje** [comment]
Can probably tweak this a bit to get a little more contrast in the early colors.

**Comment by amabirts** [comment]
When viewing on the SENSOR tab, is there a way to have the sensor name the same colour as the sensor line/marks on the graph - rather than just white?

**Comment by ziebelje** [comment]
@amabirts I presume you mean along the bottom, right?

![image](https://user-images.githubusercontent.com/3288812/104948768-d1caff00-598b-11eb-9308-392d97376a8f.png)

**Comment by amabirts** [comment]
I was thinking more along the way the floating box has the sensor name in the same colour as the line. Perhaps that could be mirrored with the key?

**Comment by ziebelje** [comment]
I believe this is possible to do with the charting library I use. I'll have to play around with it to see what can be done.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/adjust-sensor-chart-colors-to-be-easier-to-read/214/2
