### ISSUE TITLE
Add hover tooltips to sensor card icons

### ISSUE THREAD

**Issue by kevinwlau** [beestat/app#299]
At first glance, the icons in the sensor card are unintuitive - the eye and the checkmark.

![image](https://user-images.githubusercontent.com/689163/94642460-c7d0a380-02a9-11eb-891f-6f061d278460.png)

I think it would be helpful to add a tooltip on hover, either showing the current status in text (such as `Occupied` or `Unoccupied`), or what the icon is representing.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/add-hover-tooltips-to-sensor-card-icons/302
