### ISSUE TITLE
EcoBee API Changes - Dec 1, 2020

### ISSUE THREAD

**Issue by Rockstar04** [beestat/app#300]
Email from EcoBee partner program:

> Upcoming API Changes Effective December 1, 2020
> 
> The following changes will go into effect on December 1, 2020. If you are unsure whether these changes will have an impact on your solution today, we encourage you to discuss it with your technology team, program manager, other stakeholders and ecobee partners.
> 
> Access/Refresh Token Format Changes
> 
> Starting from December 1, 2020, ecobee access tokens will no longer be returned as opaque 32-character strings. Access tokens will now be JWTs, which are considerably longer and uses a wider character set. Our JWTs follow the RFC7575 standard for JSON Web Signature tokens.
> 
> To ensure your application will continue to work, you will need to ensure that your application supports the following changes:
> 
> Access tokens will be up to 7KB in length, and includes upper/lower case alphanumeric characters, hyphens, underscores, and periods.
> Refresh tokens can be of varying lengths and can contain non-alphanumeric characters.
> Authorization Code Changes
> 
> The Redirect URI associated with your registered application should be a semi-colon separated list of absolute URLs that start with https://. We do not accept http:// protocol links.
> PIN Authorization Changes
> 
> PINs will become 10 character alphanumeric strings.
> This flow is only recommended in situations where a user is interacting with a device that cannot easily use a web-based login form; we recommend migrating to the Authorization Code strategy for a better user experience.

**Comment by ziebelje** [comment]
See #269. Ecobee was kind enough to invite me into the early access for this a few months ago and we got everything squared away. No further changes should be necessary for beestat. :)

**Comment by Rockstar04** [comment]
That's great! I just got the email tonight and just wanted to make sure you were aware.
