### ISSUE TITLE
Schedule temperatures different to ecobee’s

### ISSUE THREAD

**Issue by amabirts** [beestat/app#310]
We've changed our Home schedule temperatures and noticed they are now incorrectly showing in beestat. We used to have Auto 20°C-24°C, which displayed as such. However, we've increased the heat temperature to 22°C, rather than seeing 22-24 in beestat it now shows 21.9-24.1 which seems strange. Is there any known cause for such an anomaly?

![image](https://user-images.githubusercontent.com/36783099/101553602-e25f8100-39ac-11eb-8ba7-3dc3fe87f6ec.jpeg)

![image](https://user-images.githubusercontent.com/36783099/101553616-eb505280-39ac-11eb-866f-336052df81d7.jpeg)

**Comment by amabirts** [comment]
Workaround by changing temperatures, saving, then changing back again.

**Comment by ziebelje** [comment]
Yep, that is currently the suggested resolution for this issue. Beestat is display the values exactly as they are received from ecobee.
