### ISSUE TITLE
Show/track humidity and humidifier runtime

### ISSUE THREAD

**Issue by willcassell** [beestat/app#312]
Just installed a whole house humidifier and would be cool if I could see humidity and humidifier usage.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/add-fan-humidifier-dehumidifier-etc-to-runtime-summary/102
