### ISSUE TITLE
Separate Temperature Profiles for Each Sensor (or Other Insights for Tuning HVAC System)

### ISSUE THREAD

**Issue by mattlasorsa** [beestat/app#316]
Would be great to have Temperature Profile charts for each separate sensor, which for most users correlate to separate rooms.  This would be beyond useful for balancing the temperatures and forced air distribution between rooms.

IMO, an optimal system would have minimal average deviation between set point and sensor readings for each room, which would mean minimum average delta between rooms.  One of the easiest ways to achieve this would be to have each room respond the same.  In other words, the slope of the best fit lines for heat, cool, and resist would be the same for each room.  Heat and cool profiles could be matched by adjusting the air flow to each room.  Resist lines would give insights into which rooms would benefit most from sealing of air leaks & added insulation.  These improvements, along with other changes in dwelling properties (like reducing chimney effect between floors), could be used to balance resist lines.

I can envision this going even further than the functionality of the existing Temp Profile chart, that would better assist with system tuning.  Showing the numerical slope value for each best fit line would be one example, along with other tools and insights to help dial in a system.  We could even experiment with calculating profiles and scores with all data vs temp readings taken exclusively when the room is vacant (based on motion detector feedback).  After installing a few remote temp sensors to my ecobee, I was definitely surprised by how noticeable of an effect body heat had on individual room readings.

I'll end with a quick example below using my system (3 floors, all on single zone, forced hot & cold air).  I suffer from the living room temp being consistently lower than the other rooms during the winter.  From the chart you can see that the difference in heat response is notably stronger (i.e., steeper slope) for the Bedroom and Office (both upstairs) vs the Living Room.  I need to increase air flow to the Living Room and/or reduce the airflow upstairs.  While obvious in this case, the suggested enhancement would at a minimum help identify this.  Poorer resist may also explain why the LR is typically cooler, but this isn't as easy to determine when comparing the plots of sensor reading plots.  The enhancement would help demonstrate this.

![image](https://user-images.githubusercontent.com/77788504/105360950-28704d00-5bc7-11eb-8245-53025e8287ce.jpeg)

**Comment by ziebelje** [comment]
I like that you thumbs-up'd your own post. :)

I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/separate-temperature-profiles-for-each-sensor-or-other-insights-for-tuning-hvac-system/297
