### ISSUE TITLE
Heating temperature profile not shown on graph

### ISSUE THREAD

**Issue by squirtbrnr** [beestat/app#334]
**Describe the bug**
The heating temperature profile line used to show up for one of my thermostats, but for the past 2-3 weeks there has not been a line visible.

**To Reproduce**
Open thermostat 1 and go to the temperature profile page and see a line. Go to thermostat 2 temperature profile page and see no line.

**Screenshots**
![88F5568B-4E9F-4FB7-8375-39A38BF973DD](https://user-images.githubusercontent.com/35356217/111884274-8aaeb980-898e-11eb-995f-1ceae03abda2.png)

I read the help and troubleshooting and it seems like this might be because of a couple reasons. 1) I have a 2 zone system 2) the affected thermostat sometimes runs when the unaffected thermostat runs 3) the heating runtime for this zone is typically under 3 minutes due to it being an upper level and only about ~800sqft. I’m just looking to confirm this is why the heating temperature profile line does not show up and to see if there’s anything I can do to get it back.

**Comment by sleewok** [comment]
I have a similar issue. Mine shows heat but no cooling.

I have multiple thermostats. I originally had 3 and the first I ever connected showed both heating and cooling in the temperature profile. Unfortunately that's the one I no longer use. The other two only show heating and resistance.

**Comment by ziebelje** [comment]
@squirtbrnr @sleewok Could you send contact@beestat.io an email with your thermostat serial and reference this bug? I'll have to take a closer look to see exactly why the profiles don't show up.

I did just fix a related issue that would cause profiles to not generate when adding a new thermostat (#346).

**Comment by sleewok** [comment]
Hey, the bug somehow resolved itself quite some time ago. I think it was
related to my multiple thermostats at a single location? If I remember
correctly I created a new location and moved it there and back.

**Comment by ziebelje** [comment]
Completing this one as "not a bug" and moving discussion here: https://community.beestat.io/t/add-fallback-options-for-generating-temperature-profiles/604
