### ISSUE TITLE
Thermostat & sensor detail not syncing

### ISSUE THREAD

**Issue by smellycat444** [beestat/app#337]
Thermostat detail & sensor detail not syncing. Tries for a long time to sync but eventually error messages pop up.
Worked fine yesterday when I initially signed up with Beestat.
Thermostat and sensor current temps are displaying at the top of the screen.
I have logged out of Ecobee & Beestat and tried again but no change.

**Comment by fredwalker** [comment]
Thermostat detail displayed. Graph details will not sync

**Comment by smellycat444** [comment]
My thermostat and sensor detail is all working now! If someone fixed it, thank you! Will keep an eye on it.

**Comment by ziebelje** [comment]
For anyone looking for answers, there is currently a sync issue affecting several users. More info here: https://community.beestat.io/t/sync-stopped-working/495
