### ISSUE TITLE
Sensor values over 100F show up as 0.0 in "Sensors" section

### ISSUE THREAD

**Issue by ghfields** [beestat/app#339]
I have a sensor in my attic.  Especially in the summer, it regularly goes over 100F.  Within the Beestat "Sensors" section, the temp reads 0.0 during these times.  It does not affect the Sensor Detail chart that has correctly recorded the values.

I would expect the correct temperature to be displayed or some other "non-number" indicating that it is out-of-range for the display.

**Comment by intel1212** [comment]
I see same.  This is new as sensor has shown >100 in past.Sent from my +SmartPhone
-------- Original message --------From: Garrett Fields ***@***.***> Date: 7/8/21  9:46 AM  (GMT-08:00) To: beestat/app ***@***.***> Cc: Subscribed ***@***.***> Subject: [beestat/app] Sensor values over 100F show up as 0.0 in "Sensors" section (#339) 
I have a sensor in my attic.  Especially in the summer, it regularly goes over 100F.  Within the Beestat "Sensors" section, the temp reads 0.0 during these times.  It does not affect the Sensor Detail chart that has correctly recorded the values.
I would expect the correct temperature to be displayed or some other "non-number" indicating that it is out-of-range for the display.

**Comment by ziebelje** [comment]
Give it a try now. If it doesn't immediately update wait a few minutes so the latest data syncs down.

**Comment by intel1212** [comment]
I see 3 digits now for my attic sensor.  Looks good to me!  thanks!

**Comment by ghfields** [comment]
Indeed it works now.  Fast work!
