### ISSUE TITLE
Beestat Stays Signed-In to Previous Account

### ISSUE THREAD

**Issue by reedmayhew18** [beestat/app#341]
**Describe the bug**
When signing out of an account and then signing into a different account, the app loads the previous account. This bug still happens after clearing cookies (on desktop) or reinstalling the app (on mobile), and signing out/back in on ecobee.com.

**To Reproduce**
1. Sign-in to account 1.
2. Logout of account 1.
3. Sign-in to account 2.
4. Account 1 loads as if it was still signed in.

This glitch has been reproduced on multiple mobile devices and desktop computers.

**Screenshots**
N/A

**Comment by ziebelje** [comment]
This is actually an ecobee issue/configuration. When you log out of beestat it is correctly destroying your session. When you log back in, it is correctly redirecting you to the ecobee authorization page. However, in some cases ecobee is automatically authorizing on your behalf.

I pulled up another app that integrates with ecobee the same way beestat does. Clicked authorize, logged in, approved the connection, good to go. Revoked authorization, then did the same thing again. I did not have to log into ecobee or approve the connection this time.

I'll reach out to ecobee and let them know, but you may wish to as well. If you do, it would help to test this on another service like IFTTT to rule out a third-party specific issue.

**Comment by ziebelje** [comment]
I got some help from ecobee on this and found a way to handle this on my side.

https://auth.ecobee.com/logout?federated&client_id=...&returnTo=https://beestat.io
