### ISSUE TITLE
Comparison with Nearby homes not working

### ISSUE THREAD

**Issue by jros92** [beestat/app#342]
**Description**
When trying to compare data to Nearby Homes (as opposed to Global Homes), the filter does not get applied.

**To Reproduce**
Click on "Compare" tab, try to filter the Region to "Nearby" homes, realize that the "Matching system type and stages" never changes for the region setting.
It does not matter what property type is filtered for, but that filter works. It just affects the Region filter.

Note: I just connected beestat to my ecobee about an hour ago. Maybe it just needs some time to sync the mailing address? Or maybe there are just no nearby homes for my location, so it defaults back to Global internally?

**Screenshots**
![image](https://user-images.githubusercontent.com/35766405/128394780-8dfff7cf-a3ef-4a40-9a7e-7cd567c25197.png)
![image](https://user-images.githubusercontent.com/35766405/128394867-7ed976c8-c8e1-473f-97d1-6590a474bf6d.png)

**Comment by ziebelje** [comment]
Please try this again. I had a subscription renewal issue with my address normalization service which has now been resolved.

**Comment by jros92** [comment]
> 
> 
> Please try this again. I had a subscription renewal issue with my address normalization service which has now been resolved.

Works now! :)
Thanks, this is a really useful feature!
