### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by eminphi** [beestat/app#343]
**Describe the bug**
Unable to initiate ecobee authentication.

**To Reproduce**
1. Visit beestat.io on any browser
2. Click on the Connect my ecobee button
3. URL changes to `https://auth.ecobee.com/authorize?response_type=code&client_id=nfR0LrIS7SzISwQR52go3hvgIBHgooBg&redirect_uri=https://app.beestat.io/api/ecobee_initialize.php&scope=openid%20offline_access%20smartRead&audience=https://developer-apps.ecobee.com/api/v1`
4. Firefox shows a blank page. Chrome shows an error message saying `auth.ecobee.com is currently unable to handle this request. HTTP ERROR 503`

**Screenshots**
N/A

**Comment by ziebelje** [comment]
https://downdetector.com/status/ecobee/

Ecobee appears to be having an outage of some type right now. Try again in a bit! :)

Thank you for the detailed report, though.

**Comment by eminphi** [comment]
Thank you for the quick response. Should have checked the down detector first :)
