### ISSUE TITLE
Setpoint metrics don't generate when system is set to auto

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#347]
This is working as designed. The idea was that if the system is in "auto" mode in the Winter, then you probably don't care about the cool setpoint so it's ignored. Problem is that the heat setpoint is also ignored.

End result is that people who run their system in auto all the time don't get the setpoint metric.

I think it's fine to include setpoints when the system is in auto.

**Comment by richardpeng** [comment]
Thank you!
