### ISSUE TITLE
Thermostat Summary: Incorrect year when grouped by week

### ISSUE THREAD

**Issue by crdavis12** [beestat/app#352]
When the Thermostat Summary is grouped by Week the year label is incorrect when the year wraps. It looks like the Year is set based on the last day of the week, but the Month/Date is set based on the first.

**To Reproduce**
Configure your Thermostat Summary to group by Week, with a time period that spans a year boundary.

This screenshot shows the end of 2021 and beginning of 2022, grouped by week. Notice how "Dec 27 2022" is labelled for the week of 2021-12-27 to 2022-01-02.
![image](https://user-images.githubusercontent.com/30438053/153047414-d064ce80-4a28-4285-8010-2229c42244a5.png)

Ideally I would probably put the Year label on the first week that is fully in the new year. In this case change to "Dec 27" (no year) and "Jan 3 2022". Though I could be convinced that "Dec 27 2021" and "Jan 3" is also fine.

**Comment by ziebelje** [comment]
![image](https://user-images.githubusercontent.com/3288812/212373481-cf8b1ee6-aaf7-483b-b62e-b94137641432.png)

At some point I believe I rewrote the code that generates these labels and probably fixed this either on purpose or accident. Looks fixed!
