### ISSUE TITLE
Can't zoom out to previously viewed date range in Thermostat Details

### ISSUE THREAD

**Issue by aaronschendel** [beestat/app#353]
**Describe the bug**
There appears to be no way to zoom back out to the full time range you were looking at without choosing a different range and then back to what you want.

**To Reproduce**
1. Choose Last 7 Days in Thermostat Details
2. Click and drag to select a smaller time window
3. Choose Last 7 Days to go back to the zoomed out view
4. Nothing happens

**Screenshots**
n/a

**Comment by ziebelje** [comment]
In the top right menu there's a "Reset Zoom" option. Maybe not the most obvious placement but it's there. :)

![image](https://user-images.githubusercontent.com/3288812/158173554-f379d96b-8ce1-4d8c-b8c3-57729af505fb.png)

**Comment by aaronschendel** [comment]
Woooops! Thanks for the response :)
