### ISSUE TITLE
Stuck on syncing

### ISSUE THREAD

**Issue by rajeshkannan31** [beestat/app#357]
Hi,

Can you please help me with syncing issue. Website just calls the below API in infinite loop,

https://app.beestat.io/api/?resource=thermostat&method=<XXX>

Any help in resolving the issue would be highly appreciated.

**Comment by ziebelje** [comment]
This is probably resolved now; I just fixed a bug with the sync and it resolved the other reports I had. If the issue persists send your thermostat serial number to contact@beestat.io and I'll take a closer look. Sorry!
