### ISSUE TITLE
Beestat shows the wrong average even though sensors read lower than the overall

### ISSUE THREAD

**Issue by redace4** [beestat/app#359]
My sensors read 76.5, 73.7 and 77.1 but the Beestat sensor shows 79?
Isnt it supposed to be the average so thats confusing

https://postimg.cc/fkFk3xV9

**Comment by ziebelje** [comment]
So, beestat doesn't do any of the averaging. It shows the sensor temperatures as reported by ecobee, and then the "system temperature" as reported by ecobee, which is usually some average of the participating sensors.

That said, the average temperature being reported doesn't make any sense regardless...it's higher than all of the sensors. Does ecobee's Home IQ portal show the same thing? If so I would reach out to their support to find out what's going on.
