### ISSUE TITLE
Hang on Thermostat Summary - Custom Range

### ISSUE THREAD

**Issue by crdavis12** [beestat/app#361]
**Describe the bug**
beestat hangs on me when going into the Custom Range menu for Thermostat Summary. The menu comes up blank and the X does not close it. A page refresh brings things back to normal. 

Verified on Firefox (PC) and the Android app. Started sometime in the last week.

**To Reproduce**
Analyze -> Thermostat Summary -> ... -> Custom

**Screenshots**
![image](https://user-images.githubusercontent.com/30438053/183689697-a8dcc308-ea1c-4c72-b724-2daf66e3921e.png)

**Comment by ziebelje** [comment]
Fixed; thanks for the report!
