### ISSUE TITLE
Sensor Detail tooltip values are out of order

### ISSUE THREAD

**Issue by newadventure079** [beestat/app#364]
**Describe the bug**
It looks like the Sensor Detail tooltip orders the values descending.  I've seen the values be out of order and not line up to what the graph is showing.

The Office reading is 72.8.  The Living Room is 72.4.  Yet on the graph, the Office line is lower than the Living Room line.

Also, the Office is 72.8, but it's showing well below the 72 degree y-axis label.

I'm not sure if the tooltip is wrong, or the graph is wrong, but there's a few things here not lining up.

**To Reproduce**
Look at the Sensor Detail graph and hover your mouse over to see the tooltip values.
Move around to different times on the graph and sooner or later you'll see some values that dont line up with what the graph is displaying

**Screenshots**
![Screen Shot 2022-08-16 at 12 00 18 AM](https://user-images.githubusercontent.com/84156407/184973720-e81f1116-e531-4d6b-a31f-054ffef89217.jpg)

**Comment by ECOBEE99** [comment]
September 20.  I was going to report this as well. The bar graphs on the page are not in the same order as the hover box.  This should be remedied before worrying about air quality that > 50% of users don't yet own.

Thanks in advance Jon for a quality tool!

**Comment by ziebelje** [comment]
This issue happened when you both hid the first series on a chart and then zoomed in. The tooltip was showing data relative to the entire chart, not just the zoomed region.

I believe this is actually a bug with the charting library, so I raised the issue with them here: https://github.com/highcharts/highcharts/issues/17756

Regardless, I was able to find a workaround.
