### ISSUE TITLE
Showing AUX and AUX2 in a different color or give an option to choose colors for graph.

### ISSUE THREAD

**Issue by dineshgyl** [beestat/app#369]
**Describe the bug**
I have a 2 stage AUX heat. Beestat show AUX and AUX2 as same color (Similar RED). It should show AUX2 in more different color.

**Screenshots**

![image](https://user-images.githubusercontent.com/76497238/196774822-58f1cf88-32bf-4f5a-8358-bf4fbcb90344.png)

![image](https://user-images.githubusercontent.com/76497238/196775011-e614faa7-3f9e-4634-bbef-ffc3122de545.png)

**Comment by ziebelje** [comment]
I don't have any current plans to change the defaults, but I'll combine this with an existing feature request. The eventual solution will be user-specific customization.

Closing this GitHub issue as feature request; please see here for future discussion:
https://community.beestat.io/t/adjust-sensor-chart-colors-to-be-easier-to-read/214
