### ISSUE TITLE
beestat loads for home owner but not member

### ISSUE THREAD

**Issue by aharbis** [beestat/app#373]
beestat app loads for me (owner) just fine, but my wife (member) is unable to load the app. After authenticating with Ecobee she gets the infinite loading screen from beestat app. Is this a permission issue?

We have tried clearing browser cache and running private window, does not resolve the issue.

**Comment by ziebelje** [comment]
Hi Aidan,

Unfortunately this is a limitation of the ecobee API. I don't have the ability to see thermostats you do not directly own, so anything *shared* won't show up in beestat and it ends up erroring out.

She can log in with your credentials obviously and it will work, but we're stuck with that for now. Wish I had a better answer!

Jon
