### ISSUE TITLE
Data Not Loading on Compare Tab

### ISSUE THREAD

**Issue by merikus** [beestat/app#374]
I have a bug to report with the Compare tab on beestat.

There are three data boxes on that page. Two of them are blurred out, with the word “Fetching” and a pulsing circle superimposed over the blurred boxes. The only box that is visible is “My Home.”

I’ve encountered this error on two devices, an iPad Pro an an iPhone 11. 

I hope this is helpful; if you have any questions to help resolve this bug, please don’t hesitate to let me know.

**Comment by ziebelje** [comment]
Can you send me the ecobee serial number that's having this issue? It looks to be only an issue with your account. You can post here or email to contact@beestat.io.

**Comment by ziebelje** [comment]
Closing unless I get more info.
