### ISSUE TITLE
[Suggestion] Add Contributing guidelines

### ISSUE THREAD

**Issue by tgrowden** [beestat/app#381]
I'd like to suggest that [repository contributing guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) be added to the repo so that potential contributors can follow best-practices, understand expectations of the repo owner, etc.

**Comment by ziebelje** [comment]
Did you have some interest in contributing? I haven't bothered to put together any contribution guidelines because there's been little to no interest and there's also no simple way to set up your own beestat install. It's possible I would just need to sit down and document that as well.

**Comment by tgrowden** [comment]
Yes, I'm certainly interested in contributing. I'd love documentation on getting things running--I have some thoughts on QoL features that could be nice, but I'm open to also looking into other things if you have a roadmap or list of higher priority tasks. I'd even be happy to assist with writing the documentation once I'm able to get things going myself.
