### ISSUE TITLE
Error when trying to load Compare: API call failed: json_decode()

### ISSUE THREAD

**Issue by sxdjt** [beestat/app#382]
When trying to load Compare, I am getting the following error:

"API call failed: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated"

```
{
  "success": false,
  "data": {
    "error_message": "json_decode(): Passing null to parameter #1 ($json) of type string is deprecated",
    "error_code": 8192
  }
}
```

<img width="1370" alt="Screenshot 2023-01-22 at 00 39 20" src="https://user-images.githubusercontent.com/53812540/213907455-310a6940-bca5-4dff-900d-052090a17ab2.png">

**Comment by ziebelje** [comment]
I believe this may be resolved now if you'd like to try again. I performed a server upgrade that included an upgrade from PHP 7 -> PHP 8 and have had a few lingering issues.

**Comment by sxdjt** [comment]
The original error has been resolved, but alas replaced by this one:

**API call failed: Trying to access array offset on value of type null**

```
{
  "success": false,
  "data": {
    "error_message": "Trying to access array offset on value of type null",
    "error_code": 2
  }
}
```

PHP and Python upgrades are a test of intestinal fortitude.

**Comment by ziebelje** [comment]
![image](https://user-images.githubusercontent.com/3288812/213934194-28e939ac-e25b-45d8-a520-1ddbad06b9e0.png)
No kidding. I've been monitoring logs today and just fixing as things pop up.

I believe this is now resolved.

**Comment by sxdjt** [comment]
Fixed!  Thank you!

I just discovered Beestat and will be heading over to the Patreon page shortly :)
