### ISSUE TITLE
Gaps in Detail view when Outdoor Temp is missing

### ISSUE THREAD

**Issue by crdavis12** [beestat/app#389]
**Describe the bug**
Recently I saw a chunk of time where weather data was missing from ecobee (Outdoor Temp, Wind Speed). All other data was present, but beestat is showing gaps in Indoor Temp and Comfort Profile, in the Detail views. I would expect only a gap showing in Outdoor Temp since that is the only data missing.

**To Reproduce**
Timeframe for my thermostat: 2023-03-22 10:00:00 to 2023-03-22 16:25:00 (inclusive)

**Screenshots**
![image](https://user-images.githubusercontent.com/30438053/227200489-5312fb6f-1f40-4a0b-8417-11f47b79f854.png)
![image](https://user-images.githubusercontent.com/30438053/227200608-b4bec601-da68-453d-bbd9-238bc66544bc.png)

**Comment by ziebelje** [comment]
This is intentional. For technical reasons, beestat throws away all thermostat data when the outdoor temperature is missing. It's rarely an issue so I'm ok with this concession. If it becomes more of an issue I'll look at addressing it. Thanks for the report!

**Comment by crdavis12** [comment]
That's fair. It probably complicates the calculation of temperature profiles and other things, I get that. Thanks for the quick response.

**Comment by ziebelje** [comment]
It's been a minute, but I did actually fulfill this.

**Comment by crdavis12** [comment]
Nice! Thank you
