### ISSUE TITLE
Metrics subpage on Compare tab does not display for second thermostat.  I have a multiple thermostat setup (setup as separate dwellings) and all pages are normal and correct for both thermostats (retrieving data, etc.) except "Metrics" subpage does not display for "Upstairs" thermostat.  See attached screenshots. 

### ISSUE THREAD

**Issue by chipslanier** [beestat/app#395]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots**

**Comment by ziebelje** [comment]
Hi! Could you let me know your thermostat serial number (here or via contact@beestat.io) and I can take a look. Thanks!

**Comment by chipslanier** [comment]
Thanks for your reply.  I retested and found that the ‘Metrics’ tab was now visible.  Firefox did have an update between then and now, but that shouldn’t have affected it.  I use Firefox on my iMac and MacBook as the desktop Safari will not load beestat.io <http://beestat.io/> (see attached error screenshot) although it does work well with the Safari for the iPad. This has been going on since I started using Beestat several years ago..  I assume it has something to with the login to my Ecobees that I incorrectly set way back when. 

Thanks for the reply — I appreciate your excellent work on Beestat.  It adds a lot to the Ecobee output.
-- 
Raymond H. (Chips) Lanier
28 Cypress Grove Lane, SW
Huntsville, Alabama 35824-4084
Cell:  937.313.7884
Email: ***@***.*** ***@***.***>
Public Key ID: 0x93F89C13

**Comment by ziebelje** [comment]
Deleted previous comment that contained user's personal info.

> Thanks for your reply.  I retested and found that the ‘Metrics’ tab was now visible.  Firefox did have an update between then and now, but that shouldn’t have affected it.  I use Firefox on my iMac and MacBook as the desktop Safari will not load beestat.io <http://beestat.io/> (see attached error screenshot) although it does work well with the Safari for the iPad. This has been going on since I started using Beestat several years ago..  I assume it has something to with the login to my Ecobees that I incorrectly set way back when.
> 
> Thanks for the reply — I appreciate your excellent work on Beestat.  It adds a lot to the Ecobee output.
