### ISSUE TITLE
Temperature Profiles missing Cool 2 and Heat 2

### ISSUE THREAD

**Issue by robkap** [beestat/app#396]
My Temperature Profile has Aux heat 1 & 2, but for Cool and ASHP Heat it only shows a line for Stage 1 operation, not Stage 2.

<img width="1658" alt="Screenshot 2023-06-01 at 11 48 45 AM" src="https://github.com/beestat/app/assets/4606963/ed3ef0e7-a97a-44ff-b110-a02ad0136107">

**Comment by ziebelje** [comment]
Typically this is due to a lack of data. If beestat doesn't have enough suitable samples for an accurate profile, that specific profile won't generate. I suspect Cool 2 will generate as the Summer continues and you run that more often. It might be Winter until you see Heat 2, though.
