### ISSUE TITLE
CSV downloaded data unusable due to data misalignment: some rows missing TVOC and CO2 cells shifting rightward cells to the left

### ISSUE THREAD

**Issue by robkap** [beestat/app#397]
Viewing downloaded/exported beestat data, some cells are missing and cells to the right of missing data is shifted left, messing up the column alignment for those rows. 
This renders the CSV unusable without manual data alignment.

Rows with messed up/missing data are the ones with IAQ in certain ranges:
IAQ between approx 3000-6000 is correlated with both TVOC and CO2 cells being empty and all cells to the right shifted left by 2 cols.
IAQ greater than 16000 is correlated with TVOC cells being empty and all cells to the right shifted left by 1 col.

**Comment by ziebelje** [comment]
Would you mind providing your thermostat serial number? I don't see this issue present when I download data on my account. You can share it here or email contact@beestat.io. Thank you!

**Comment by ziebelje** [comment]
Confirmed the issue after looking at a specific date range for your account. Will address and get fixed.

**Comment by robkap** [comment]
Fantastic! Thank you!

<> Rob
