### ISSUE TITLE
Self-Hosted Beestat issue..

### ISSUE THREAD

**Issue by wangel** [beestat/app#399]
I had the app setup, selfhosted, running great.... then I decided to do a "git pull" and update it.

Now I'm getting an error that Greedo shot first! ....

API call failed: Out of range valume for column 'air_quality' at row 1

I assume it's probably because I need to update something in the Database, but the beestat.sql file is a blank db, so it will dump all my data?

Sorry, it's probably and easy fix.

thank you!

**Comment by ziebelje** [comment]
I try to update beestat.sql if the database changes, so look at that file when you `git pull` to see if you need to change anything. You don't want to re-run it, just do whatever alter you need to get the database change.

I post the actual update queries in Discord. In this case, do:

```
update `runtime_thermostat_summary` set `sum_degree_days` = 0;

alter table
  `runtime_thermostat_summary`
change
  `sum_degree_days` `sum_heating_degree_days` smallint unsigned not null after `sum_economizer`,
add
  `sum_cooling_degree_days` smallint unsigned not null after `sum_heating_degree_days`
;
```

**Comment by wangel** [comment]
Ok, cool.  I ran the following and it updated 380 rows each time, but I am still getting the error.

Here's a small snippet of the error that gets thrown out ... it will keep going and eventually crash the browser window.  Before I cut it down it was 23,814 lines... hahaha

https://pastebin.com/9njW9L0W
