### ISSUE TITLE
UX: Show 'better than X% of homes' in comparison rather than `>` or `<` 

### ISSUE THREAD

**Issue by onionhammer** [beestat/app#402]
Less than or greater than have no inherent meaning to the end user on the comparison page, I think it would be much clearer to either

A) Show "Better than X% of homes" 
or
B) Indicate "lower is better" or "higher is better" somewhere for each stat in a tooltip on each card.

Obviously this only works for some of the stats, where age of homes isn't "better" or "worse", but you could substitute "better" for "newer" or something

**Comment by ziebelje** [comment]
The idea is nice, but I moved away from subjective terms like better/worse and generalized descriptions like "x is better" a while ago. Beestat is unopinionated.

My reasoning is that it's not really my place to decide whether or not, for example, a lower setpoint is "better" in the winter. What if someone in the home has a medical condition that necessitates a higher temperature? Beestat shows the data, it's up to the user to decide what is better or worse for their own situation.

**Comment by onionhammer** [comment]
@ziebelje Ok, I literally don't even know what to what when I see "Runtime Per Degree Day", I know there's a documented explanation out there, but "> 80%" is not a useful metric of whether thats desirable or not.. it's literally just not even useful for folks who don't fully grok what that means or the impact of that measurement. Bad user experience.
