### ISSUE TITLE
Duplicate entry Error code 1062

### ISSUE THREAD

**Issue by Fibril-vested** [beestat/app#403]
beestat Analyze and compare tabs fail with following error code. May need some additional sanity checking around line 653 in api/runtime.php

API call failed: Duplicate entry 'xxxxx-xxxxx-2023-12-16' for key 'profile.user_id_thermostat_id_date'

Sorry about that! This error has been logged and will be investigated and appropriately punished. Please reach out to contact@beestat.io if it persists.

{
  "success": false,
  "data": {
    "error_message": "Duplicate entry 'xxxxx-xxxxx-2023-12-16' for key 'profile.user_id_thermostat_id_date'",
    "error_code": 1062
  }
}

**Comment by Fibril-vested** [comment]
Issue goes away next calendar day.

**Comment by ziebelje** [comment]
This issue has been increasing in frequency lately. It appears to always resolve itself, but needs more investigation. Another user said this:

`Marked and then unmarked the ignore solar gain, which caused the temperature profile to regenerate, instantly fixed it on both online and self hosted versions`

**Comment by ziebelje** [comment]
Another user:

> I was fiddling with the app when I changed the date for data gathering in the settings and the app gave me an error and now I can’t see stats as it’s saying there is a duplicate profile.
