### ISSUE TITLE
One of my two thermostats isn't syncing data. 

### ISSUE THREAD

**Issue by sgringer** [beestat/app#406]
**Describe the bug**
One of my thermostats is stuck syncing. 
I tried downloading data and the rows since 6:45am (it's now 10:15am) are empty. Timestamps but no data (see gif).
No outages or issues reported for Ecobee services.
My other thermostat and paired satellite in the same property are not experiencing issues.

**To Reproduce**
Simply loaded beestat.

**Screenshots**
![2024-01-15_screenshot_beestat  My ecobee_000493](https://github.com/beestat/app/assets/12450771/80887780-1ecd-4293-bd24-266a0c30c65a)
![2024-01-15_screenshot_ecobee comconsumerportalindex html#my-appsdetails59D26539974490A6B2C87F604A98A388D61CEE645B056866234F65D01F7112E58CE66EE394D912CF7D9D2AABC0EAF0C7BC5A1D8C403634BD0B526F32CE4C446206A1775C87336FBC41BB3AC0AE1D84C7_000495](https://github.com/beestat/app/assets/12450771/0d8d80a6-5c84-4c7a-9696-99e132295de6)
![2024-01-15_screenshot_Beestat Export - 531659810242 2_000496](https://github.com/beestat/app/assets/12450771/175e2448-9b29-48d1-80b7-6cb0765d1e90)

**Comment by sgringer** [comment]
After I posted this, I got a rate limit error. What causes this and is there something I need to do in order to avoid? 
![2024-01-15_screenshot_beestat  My ecobee_000498](https://github.com/beestat/app/assets/12450771/e8e3e923-1fa7-4152-bf5d-ce967e646c3b)

**Comment by ziebelje** [comment]
I suspect this may now be resolved as there was high usage on beestat yesterday. I added some capacity to the backend and most of these issues went away.

I'll close this ticket, but if you're still having trouble, send your thermostat serial number to contact@beestat.io and I can take a closer look at your account.
