### ISSUE TITLE
Setpoint reporting is way off

### ISSUE THREAD

**Issue by PHolstein1** [beestat/app#410]
**Describe the bug**
In the Analyze section of Beestat, the system reports that my setpoint temperature for cooling is 57 degrees.  For the record, I have several setpoints in my stem from 68 degrees to 73 degrees.  None are as low as this, and I have no idea where the 57 degrees is coming from.

**To Reproduce**
Just pull up the analyze report.

**Screenshots**
<img width="757" alt="Screenshot 2024-05-24 at 9 36 00 PM" src="https://github.com/beestat/app/assets/51170470/daf34631-3581-452d-b1b9-ac4bfd2b9656">

**Comment by ziebelje** [comment]
Could you send me your thermostat serial number? Here is fine, or you can send to contact@beestat.io and reference this bug. I'll take a look.

**Comment by ziebelje** [comment]
Turns out there are situations where the thermostat is set to "cool" and does *not* have a cool setpoint defined. I didn't assume that would happen, so the setpoint mean was including a bunch of null/zero values and artificially lowering the value. Fixed.
