### ISSUE TITLE
Thermostat detail data not available after thermostat replacement

### ISSUE THREAD

**Issue by thewinkelman** [beestat/app#412]
**Describe the bug**
After replacing one of my ecobees, the beestat detail and analysis views are not showing any graph data for the new thermostat. The detail graphs show "syncing".

**To Reproduce**
Switch to the detail or analysis view.

**Screenshots**
![Screenshot 2024-06-21 at 17 15 31](https://github.com/beestat/app/assets/4997824/9fd2c61c-e662-4bc3-b79a-dd1aaaf5cecb)

**Comment by thewinkelman** [comment]
I guess I was not waiting long enough. I checked back a few hours later and it was reporting as expected.

**Comment by gpz1100** [comment]
Having encountered this myself recently, it appears there's a 5hr delay from the time new thermostat comes online before data is visible in beestat (or homeiq).
