### ISSUE TITLE
Checking: is self-hosting impossible unless you already have a developer account?

### ISSUE THREAD

**Issue by erik434** [beestat/app#417]
Hello! I just discovered Beestat and I was curious about self-hosting my own instance for fun, but it seems like an Ecobee developer account is required to do so. I just wanted to double check my understanding of your documentation - am I totally out of luck since they aren't allowing new dev account registrations anymore? Thanks! :)

**Comment by cswelin** [comment]
Yes unfortunately a developer account would be required as you wont be able to fetch the thermostat data without a developer account. 

Colin 
ecobee iOS engineer

**Comment by ziebelje** [comment]
Thanks @cswelin! Hopefully things get opened back up soon. 🤞

**Comment by sporkman** [comment]
I know this is closed, but I was working with their support on an unrelated issue (electric baseboard heat w/a giant honeywell relay), and I asked about the dev program. It sounds like they're actually going to re-open it, supposedly bigger and better? This is what the support agent said:

> I’m glad you’re enjoying your ecobee! I apologise as I do not have a specific date for when the Developer API will open again, but rest assured it is currently going through improvements for when it does open back up. You can check back on our website periodically for updates!

**Comment by erik434** [comment]
Thanks for the update @sporkman! That's happy news - I'll keep an eye out :)
