### ISSUE TITLE
Custom report/PDF generation

### ISSUE THREAD

**Issue by edgariscoding** [beestat/app#42]
It'd be awesome if we had the choice or option to export a snapshot of the data displayed as a PDF. 

I'd like to send the report to my home warranty company because they sent a tech out and he claims to have fixed our AC but it has been running for 19 hours without cooling the house a single degree.

This would be useful

EDIT: Just noticed the download button for each chart! Nice, but it'd be awesome if we could download the entire report 😛

**Comment by ziebelje** [comment]
Exporting a full website as a PDF is a somewhat tricky technical endeavor. It basically requires you to render the entire website on the server, then take a screenshot of it. There's no way to do it natively in a web browser.

Regardless, I'll mill this one over. Maybe something has changed lately. 

Your options at present are:
1. Download each individual chart (as you've seen)
2. Print the website to a PDF
3. Use a browser extension like [Full Page Screen Capture](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en) which has the ability to screenshot the entire page and export as a PDF.

**Comment by ziebelje** [comment]
I'm going to no to just generically exporting the dashboard as a PDF document for a few reasons:
1. There are third party options as mentioned above
2. It's not trivially possible with JavaScript to do this. The available ways to do this get weird fast
3. The dashboard may transform in the future to something a bit different that would not be suited to a full page export
4. I don't believe this would be a highly utilized feature

I'm going to keep this issue open, though, as I still like the idea of being able to export reports of some kind. Maybe you're having thermostat issues and you want to print out a customized report for some specific date range or something. I'll keep this as a low priority idea for now.

**Comment by ziebelje** [comment]
I've decided not to pursue this further. The individual graph exports make it relatively easy to share the data where necessary. The third party options handle the uncommon use case of exporting the entire page. I cannot think of any use case for exporting customized reports of any sort that would be worth the effort.
