### ISSUE TITLE
Recent Activity - Humidity

### ISSUE THREAD

**Issue by ziebelje** [beestat/app#60]
Need a different version of the Recent Activity graph that focuses on humidity. There is outdoor humidity, indoor humidity, desired humidity, humidifiers, and dehumidifiers.

My current vision for this is some way to add your own custom graphs. So "Recent Activity" would be a graph type, then you could choose all of the data you want to show. There may be some defaults to help you decide, or you could craft your own.

**Comment by coli** [comment]
Please see the 10 day chart at wunderground, the indoor + outdoor dew point line is the most useful

**Comment by ziebelje** [comment]
They've got some cool stuff on their graph. I'll keep this in mind when I revisit this. Thanks for the feedback!

![image](https://user-images.githubusercontent.com/3288812/50869195-fe051b80-1380-11e9-8dfd-9388dc59effd.png)

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/recent-activity-humidity/331
