### ISSUE TITLE
Show heating graph in Runtime Summary as negative values

### ISSUE THREAD

**Issue by kasmca** [beestat/app#77]
Is it possible to show the heating graph values as negative numbers so they have a correlation to the outside cold temperatures.  Currently in the aggregate graph, if the temperature goes down, the amount of heating goes up.  Visually it would be more helpful to have these in the same direction for correlation.

This is done on Ecobee IQ graphs for Weather Impact.

**Comment by FrankXLT** [comment]
Agreed. I am not sure ecobee understands data analysis anyway.

**Comment by ziebelje** [comment]
I may do this yet, but if so it'll be a configurable thing.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/show-heating-graph-in-runtime-summary-as-negative-values/329
