### ISSUE TITLE
Custom schedule in Recent Activity not having correct name

### ISSUE THREAD

**Issue by vincep5** [beestat/app#78]
I have a Custom comfort setting of Work which starts at 8:30, but the graph of Recenty Activity is picking up a differently named comfort setting.  If I go to the ecobee UI and re-name it, when i log back into your site, it updates it with the new name.  In fact even on Saturday, it is displaying the wrong name for the custom schedule.  It seems as if it only picks one of the comfort settings names instead of the real one.

**Comment by vincep5** [comment]
![snip](https://user-images.githubusercontent.com/26965876/49332495-60455200-f573-11e8-8c84-fc4ba33ab23f.JPG)

**Comment by ziebelje** [comment]
I believe this is the same issue described in #65 here: https://github.com/ziebelje/beestat-issues/issues/65#issuecomment-439518957

Issue #65 is now fixed anyways, so the bug that was causing incorrect data to show should now be fixed.
