### ISSUE TITLE
Add humidity and specific heat to Runtime Summary

### ISSUE THREAD

**Issue by FrankXLT** [beestat/app#81]
This might be a fun feature to have... To see how much energy is in the air.

**Comment by ziebelje** [comment]
I'm not sure that specific heat is terribly relevant, but humidity possibly. If I were to add humidity I think I would do it at a later data as part of an "advanced" section that allows more dynamic customization of graph contents. Then, for the people who want it, they could pull humidity or indoor temperature or whatever other columns they want. Heck, at that point I could allow you to enter a formula if you want to get scientific about things. :)

For now I'll mark this as an idea and revisit when I get into more customization.

**Comment by ziebelje** [comment]
I am migrating all feature requests to the beestat community to take advantage of more discussion and features like voting. Feel free to create an account there to follow and vote on this request!

https://community.beestat.io/t/add-humidity-and-specific-heat-to-runtime-summary/328
