### ISSUE TITLE
Recent Activity should be able to show more than 7 days

### ISSUE THREAD

**Issue by coli** [beestat/app#86]
I would love it if it can show 1 month, 1 year, all times.

**Comment by ziebelje** [comment]
The issue with displaying a detail graph at such a macro scale is that:
1. It's cramming a ton of data into a small area, at which point it basically becomes unreadable
2. It's incredibly intensive on both the server and the client. The best I could even get the server to respond to with default setting is 90 days. That's 25,000 data points for each series.

Just for fun here are 30/90 day graph examples:
![ziebee - recent activity - 30](https://user-images.githubusercontent.com/3288812/50868833-5804e180-137f-11e9-9deb-d186b9dcfb59.png)

![ziebee - recent activity - 90](https://user-images.githubusercontent.com/3288812/50868836-5a673b80-137f-11e9-9216-a1244461d50a.png)

Can I ask what you're looking for with that kind of time period on this graph? I'm not opposed to getting more data in your hands but I don't know that this graph is the place for it.

**Comment by coli** [comment]
It's also from weather underground, eg go here and switch into yearly view

https://www.wunderground.com/personal-weather-station/dashboard?ID=KFLPENSA119&cm_ven=localwx_pwsdash#history/s20180107/e20190108/myear

the runtime bar is not useful zoomed out like that, but if you group them say weekly, then overlay them on the temp chart like how ecobee does it on their weather impact chart, that could be very interesting to see.

**Comment by ziebelje** [comment]
I think I'm going to extend the Recent Activity chart to support up to 30 days (with options of 1, 3, 7, custom). Anything past 30 days belongs on the Aggregate Runtime chart, which has all of the features of Ecobee's Weather Impact chart.
